### ISSUE TITLE
Add possibility to download Teamcity distributive

### ISSUE THREAD

**Issue by grundic** [rodm/gradle-teamcity-plugin#1]
Hello!
First of all, great work :)
I found another example of gradle build script and there is possibility to download Teamcity distributive into plugin development folder, here it is: https://github.com/greggigon/TeamCity-Crowd-Plugin/blob/master/build.gradle
Would it be possible to implement same functionality in your plugin?
Perfectly, it would be great if it would be possible to launch Teamcity with installed plugin right from gradle.

**Comment by rodm** [comment]
The plugin now supports downloading a TeamCity distribution, deploying the plugin and starting and stopping both the server and build agent. If you're ok with it I'll close this issue.

**Comment by grundic** [comment]
Awesome! Should be incorporated in default plugin development pipeline :)
Thank a lot!
