### ISSUE TITLE
Supply maven archetypes

### ISSUE THREAD

**Issue by grundic** [rodm/gradle-teamcity-plugin#16]
First of all: great, awesome plugin! It's so much easier to develop with help of it. Thank you, man! Why it's still not a default and recommended way? 👍 

And now my problem: each time I'm going to create new plugin, I have to create the structure for it, copy build.gradle from previous project, do not forget descriptors... Arhh..
I don't know whether it's a good idea and responsibility of your plugin, but it would be quite nice to provide maven archetypes for creating plugin skeleton with initial structure. Something similar to [Jetbrain's](https://confluence.jetbrains.com/display/TCD10/Developing+Plugins+Using+Maven), but initialized with your plugin inside.

**Comment by rodm** [comment]
Thanks for the feedback.

I've looked into Gradle's equivalent for archetypes in the past but while the Gradle team do have plans its not the highest priority from what I've read on a few forum posts. As for adding support to this plugin, I don't think it would be a suitable responsibilty. A separate plugin would be better, possibly something that could be applied in a global init script making it available in any project.

**Comment by grundic** [comment]
Well, then it could possibly be implemented with help of [cookiecutter](https://github.com/audreyr/cookiecutter).
Thanks for response!
