### ISSUE TITLE
Stop takes forever

### ISSUE THREAD

**Issue by tulikagupta** [rodm/gradle-teamcity-plugin#2]
If any build is running gradle task and I try to stop/cancel build. It takes forever .

**Comment by rodm** [comment]
Can you provide more details, its not clear to me if you are talking about stopping a build using the TeamCity UI or calling one of the stop tasks available in this plugin, such as stopServer or stopAgent.

**Comment by tulikagupta** [comment]
Yes, if I try to stop using Teamcity UI.

**Comment by rodm** [comment]
Ok, this project is for a Gradle plugin to build and package TeamCity plugins, it's not the Gradle build runner that comes with TeamCity. You should try the TeamCity forums and bug tracker at the following site https://teamcity-support.jetbrains.com/hc/en-us
