### ISSUE TITLE
Server plugin is not rebuilt when I change descriptor

### ISSUE THREAD

**Issue by jonnyzzz** [rodm/gradle-teamcity-plugin#27]
I have variables in my build that defineds versions and other string attributes. 
Changing those variables does not make Gradle to re-build the server-side plugin
Looks like TeamCity descriptor is missing from cache key somewhere

**Comment by rodm** [comment]
I've been unable to re-create your problem. I tried changing the version in the root project of the [Gradle Build Cache](https://github.com/rodm/teamcity-gradle-build-cache-plugin) plugin and running the `serverPlugin` task, this correctly re-packages the plugin zip file with the updated descriptor.
Can you provide the tasks you're executing and an example project?

**Comment by rodm** [comment]
@jonnyzzz is this still a problem for you? I recently discovered that changes to the agent-side descriptor didn't repackage the agent side plugin and that would then lead to the server side not being repackaged. This is has been fixed and is available in v1.1-rc-1 of the plugin.

**Comment by jonnyzzz** [comment]
Thanks. I've updated to the latest version now. I'll let you know if the problem is still here, thanks!
