### ISSUE TITLE
Provide some progress to 'downloadTeamCity' task

### ISSUE THREAD

**Issue by VladRassokhin** [rodm/gradle-teamcity-plugin#3]
For now it's looks like hanged,  but actually it downloads file.
It would be nice to at least print what file is downloading right now (as gradle does for dependencies)

**Comment by VladRassokhin** [comment]
Thank you for fast fix!

**Comment by rodm** [comment]
The classes used to provide this fix were internal Gradle classes that have been removed in a recent release, this means the plugin can't be used with newer versions of Gradle. I've created a new issue, #9, to revert the change to fix this issue and #10 to add progress logging again when Gradle provides an API.
