### ISSUE TITLE
why are "agent" and "server" configurations non-transitive

### ISSUE THREAD

**Issue by Vampire** [rodm/gradle-teamcity-plugin#42]
I currently make my build now multi-target-version-able, to support the reloadable flag for 2018.2 but stay compatible wiht 2018.1.
I tried to do 

```groovy
configure([project(':server'), project(':serverPre2018.2')]) {
    jar.enabled = false
    dependencies {
        agent project(path: ':agent', configuration: 'plugin')
        server project(':commonServer')
    }
}
```
but that missed the transitive dependencies of `commonServer` (the JAR from sibling project `common`).
I had to change it to
```groovy
configure([project(':server'), project(':serverPre2018.2')]) {
    jar.enabled = false
    dependencies {
        agent project(path: ':agent', configuration: 'plugin')
        runtimeOnly project(':commonServer')
    }
}
```
to get the transitive dependencies packed.

**Comment by rodm** [comment]
Looking through the history of the code the first configuration was the `agent` configuration and it was used to include the agent-side plugin zip in the server-side zip file. The configurations were most likely a result of copy-paste, I've had a look at a few projects that use the `agent` and `server` configruations and don't see a problem change it.

**Comment by Vampire** [comment]
Thanks, works better now I think
