### ISSUE TITLE
Inconsistency with dependencies and versions <9

### ISSUE THREAD

**Issue by Vampire** [rodm/gradle-teamcity-plugin#44]
I've seen that you handle these inconsistent between server and agent part.
For server part you warn and exclude the dependencies from the descriptor.
For agent part you warn but include the dependencies in the descriptor.
Is this difference intended?

**Comment by rodm** [comment]
It wasn't intended, I had noticed it awhile back but decided because it only affects building agent-side plugins for TeamCity 8.x, which hasn't been updated since 2014, that there was no need to make it consistent. So I'll close this as a wontfix.
