### ISSUE TITLE
Please support token for publishing

### ISSUE THREAD

**Issue by Vampire** [rodm/gradle-teamcity-plugin#49]
In Hub you can create tokens that have access only to the plugin repository and you don't need to store username / password on disk or enter it for publishing.
Would be nice if the plugin would support the usage of such a token instead of username / password.
It seems the library you use for uploading already supports both, so it should be a fairly easy implementation.

**Comment by rodm** [comment]
It was easy to change and I've published v1.2.1 of the plugin with support.

**Comment by Vampire** [comment]
Cool, thanks :-)
