### ISSUE TITLE
Support for update notes

### ISSUE THREAD

**Issue by Vampire** [rodm/gradle-teamcity-plugin#51]
When releasing my plugin, I want to fill in the update notes.
As far as I can see the plugin does not yet provide that.

**Comment by Vampire** [comment]
And if I interpret the website correct, it is one update notes for all releases, so an option to add the given notes to the top or bottom of the existing ones would also be nice if possible.

**Comment by rodm** [comment]
I had looked into this awhile back and discovered that changes notes come from the plugin descriptor for IDEA plugins, which the TeamCity plugin descriptor doesn't have. The issue [MP-2369](https://youtrack.jetbrains.com/issue/MP-2369) is a request to support changes notes for TeamCity plugins.

**Comment by Vampire** [comment]
Oh, that is bad. :-(
Btw. I also opened https://youtrack.jetbrains.com/issue/MP-2500 which is related.

**Comment by Vampire** [comment]
MP-2369 is closed as implemented now. :-)
