### ISSUE TITLE
Support TeamCity versions with '-SNAPSHOT' 

### ISSUE THREAD

**Issue by missingdays** [rodm/gradle-teamcity-plugin#55]
When deveoping plugins for the nighlty TeamCity, it's impossible to set teamcity version to any version that ends with '-SNAPSHOT', e.g. '2020.1-SNAPSHOT'.
This is a valid TeamCity version, yet it can't be set

**Comment by rodm** [comment]
While '2020.1-SNAPSHOT' isn't supported you can set the version to just 'SNAPSHOT'. This support was added by PR #22 to support developing against unreleased versions of TeamCity.

**Comment by subelta** [comment]
@rodm 
problem is, you can’t download “SNAPSHOT” from 
https://download.jetbrains.com/teamcity-repository/org/jetbrains/teamcity/server-web-api/, 
because there are only “-SNAPSOT” versions, so either I use SNAPSHOT and teamcity is not found or I use XXXX.X-SNAPSHOT(which is actually there) and plugin dismisses it as invalid

**Comment by rodm** [comment]
@subelta @missingdays Ok, what I propose to do is add a property to allow snapshot versions, this will be disabled by default maintaining the current behaviour. Do you have thoughts on this idea?

**Comment by missingdays** [comment]
@rodm is there a reason to explicitly prohibit the use of `202X.X-SNAPSHOT` versions at all? I don't see a problem in allowing them by default, without properties

**Comment by rodm** [comment]
The only reason is to avoid depending on an unreleased API that could change before release. Certainly for third party plugin developers they should only develop against released versions, so I see this change only being useful to TeamCity developers who have an insight into new APIs being developed.

**Comment by missingdays** [comment]
> depending on an unreleased API that could change before release

That's the usual assumption if you are developing against `snapshot` version, I beilive

But ok, property would be fine for me too.
