### ISSUE TITLE
Create a deployable zip package

### ISSUE THREAD

**Issue by michaeloa** [rodm/gradle-teamcity-plugin#64]
Maybe I'm missing something obvious, but the plugin does not seem to have any target to build a packaged plugin zip file?

That would seem like useful functionality to have, since packaged plugins can be installed manually on environments.

**Comment by michaeloa** [comment]
Ah - forget my mentioning this. Seem to have missed a setup - now I see it being generated under the server in build/distributions.

Would suggest adding this to the README in case others are looking for the same functionality.

**Comment by rodm** [comment]
I've added more to the description of the `serverPlugin` task
