### ISSUE TITLE
deployTo task doesn't fully work on 1.4-beta-1 version

### ISSUE THREAD

**Issue by missingdays** [rodm/gradle-teamcity-plugin#66]
Steps to reproduce:

1. Run `deployTo` task
2. Go to `Plugins` page

Expected result:
Deployed plugin is fully reloaded

Actual result:
Plugin is not reloaded, page shows the button to reload the plugin

Everything worked as expected in version `1.3.1` so I think something broke in version `1.4-beta-1`

**Comment by rodm** [comment]
Thanks for the report, I've found the problem and hope to have fix soon.

**Comment by rodm** [comment]
@missingdays the fix for this issue is now available in verision `1.4-beta-2` of the plugin.
