### ISSUE TITLE
Option AllowSnapshotVersions doesn't work

### ISSUE THREAD

**Issue by dimyriy** [rodm/gradle-teamcity-plugin#78]
Good afternoon, I see that in 1.4 version of plugin there's a new option allowing snapshot versions of teamcity to be used. It's implemented in https://github.com/rodm/gradle-teamcity-plugin/issues/55. However, this option doesn't seem to work, as when I'm trying to build my project it still says 
`'2021.2-SNAPSHOT' is not a valid TeamCity version string (examples: '9.0', '10.0.5', '2018.1')`.

**Comment by rodm** [comment]
@dimyriy I've been able to re-create the problem and hope to have a fix soon.

**Comment by dimyriy** [comment]
Thank you!
