### ISSUE TITLE
Support new TeamCity versioning scheme

### ISSUE THREAD

**Issue by dmitry-treskunov** [rodm/gradle-teamcity-plugin#80]
See https://blog.jetbrains.com/teamcity/2021/12/announcing-the-new-versioning-scheme-and-retiring-of-the-teamcity-early-access-program/

From now TeamCity versions are named liked 2022.04 or 2022.04-SNAPSHOT, please support it in the plugin otherwise I'm getting the following error:

'2022.04-SNAPSHOT' is not a valid TeamCity version string (examples: '9.0', '10.0.5', '2018.1')

**Comment by rodm** [comment]
Snapshot versions are supported with version 1.4.1, see #55, and require adding `allowSnapshotVersions = true` to the `teamcity` configuration block for each project. The changes to the version scheme in the above link are also supported.
